config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :organisations
  resources :campaigns, only: [ :new, :create ]

  resources :materials do
    resources :instructions, only: [ :create, :new ]
  end

  resources :campaigns, only: [ :index, :show, :edit, :update ] do
    resources :questions, only: [ :create ]
    resources :package, only: :create do
      resources :missions, only: [ :new, :create ]
    end
    collection do
      get :my_campaigns
    end
    member do
      get :dashboard
      patch :publish
      patch :pause
      patch :finish
      get :duplicate
    end
  end

  resources :questions, only: [ :update, :destroy ] do
    member do
      patch :seen
    end
  end

  resources :instructions, only: [ :edit, :destroy, :update ]
  resources :users, only: [ :index, :show ]
  resources :missions, only: [ :index, :show, :update ] do
    collection do
      get :my_missions
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :missions
  has_many :packages, through: :missions
  has_many :organisations
  has_many :questions
  has_many :campaigns, through: :organisations

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :xp, numericality: { only_integer: true }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = policy_scope(User).all
    @user_position = position_of(current_user)
    @top_50 = User.order(:xp).first(50).reverse
  end

  def show
    @user = current_user
    @organisations = current_user.organisations
    @user_position = position_of(@user)
    authorize @user
  end

  private

  def position_of(user)
    User.order(:xp).reverse.find_index(user) + 1
  end
end

app/views/users/index.html.erb
<div class="home-banner mb-4" style="background-image: url(<%= image_path('leaf-illus.png') %>);">
  <div class="container">
    <div class="d-flex align-items-center justify-content-between">
      <h4 class='mt-3'>
        <%= link_to missions_path do %>
          <i class="fas fa-arrow-left text-light"></i>
        <% end %>
      </h4>
      <h3 class="mt-3 flex-grow-1 text-left ml-5">Classement</h3>
    </div>
  </div>
</div>

<div class="container" style="margin-bottom: 75px;">
  <ul class="list-group">
    <% @top_50.each_with_index do |user, index| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
          <span class="mr-3"><%= "##{index + 1}."%></span><%= user.first_name %>
          <% if user == current_user %>
            <span class="badge badge-info badge-pill ml-3">you</span>
          <% elsif user.admin %>
            <span class="badge badge-dark badge-pill ml-3">admin</span>
          <% end %>
        </div>
        <div class="d-flex">
          <span class="badge badge-primary badge-pill"><i class="fas fa-chart-line"></i> <%= user.xp %></span>
        </div>
      </li>
    <% end %>
    <% if @top_50.count > 50 %>
      <li class="list-group-item d-flex justify-content-between align-items-center">...</li>
    <% end %>
    <% if !@top_50.include?(current_user) %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
          <div class="d-flex align-items-center">
            <span class="mr-3"><%= "##{@user_position}." %></span><%= current_user.first_name %>
            <% if current_user %>
              <span class="badge badge-info badge-pill ml-3">you</span>
            <% elsif current_user.admin %>
              <span class="badge badge-dark badge-pill ml-3">admin</span>
            <% end %>
          </div>
          <div class="d-flex">
            <span class="badge badge-primary badge-pill"><i class="fas fa-chart-line"></i> <%= current_user.xp %></span>
          </div>
        </li>
      <% end %>
      </div>
    </li>
</ul>
</div>

app/views/users/show.html.erb
<div class="home-banner" style="background-image: url(<%= image_path('leaf-illus.png') %>);">
   <div class="container">
      <div class="d-flex align-items-center py-3">
         <% if @user.photo.attached? %>
            <%= cl_image_tag @user.photo.key, height: 40, width: 40, crop: :fill, class: "avatar mr-3" %>
         <% else %>
            <img src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" class="avatar mr-3">
         <% end %>
         <h2 class="mb-0 flex-grow-1 "><%= @user.first_name %></h2>
         <div class="circle d-flex justify-content-center align-items-center plastroc-text-shadow">
            <%= link_to destroy_user_session_path, method: :delete, class: 'p-3' do %>
               <i class="fas fa-sign-out-alt text-primary plastroc-text-shadow" id="logout"></i>
            <% end %>
         </div>
      </div>
   </div>
</div>

<div class="container" style='margin-bottom: 65px'>

  <!-- Profiles info -->
  <div class='d-flex align-items-center justify-content-between'>
   <h4 class="mt-3 flex-grow-1">Profile</h4>
   <h6 class='mt-3'>
      <%= link_to edit_user_registration_path, class: 'mt-3 mb-1 mr-1' do %>
         <i class="fas fa-pen"></i>
      <% end %>
   </h6>
  </div>
  <hr class="mb-3">
  <p><i class="far fa-user mr-2"></i> <%= @user.first_name %> <%= @user.last_name %></p>
  <p><i class="fas fa-envelope mr-2"></i> <%= @user.email %></p>
  <% if @user_position == 1 %>
    <p><i class="fas fa-trophy mr-2" style="color: #ffd90f;"></i> #<%= @user_position %></p>
  <% elsif @user_position == 2 %>
    <p><i class="fas fa-trophy mr-2" style="color: #b4babd;"></i> #<%= @user_position %></p>
  <% elsif @user_position == 3 %>
    <p><i class="fas fa-trophy mr-2" style="color: #cb8524;"></i> #<%= @user_position %></p>
  <% else %>
    <p><i class="fas fa-trophy mr-2"></i> #<%= @user_position %></p>
  <% end %>
  <p><i class="fas fa-chart-line"></i> <%= @user.xp %> xp</p>


  <!-- My organisations -->
  <% if !current_user.organisations.empty? %>
    <div class='d-flex align-items-center justify-content-between'>
      <h4 class="mt-3">Organisations</h4>
      <h6 class='mt-3'>
        <%= link_to new_organisation_path, class: 'mt-3 mb-1 mr-1' do %>
          <i class="fas fa-plus"></i>
        <% end %>
      </h6>
    </div>
    <hr class="mb-3">
    <% @organisations.each do |org| %>
      <%= link_to organisation_path(org), class: 'text-decoration-none' do %>
        <div class="d-flex flex-row card card-s">
          <% if org.photo.attached? %>
            <%= cl_image_tag org.photo.key, crop: :fill %>
          <% else %>
            <img src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
          <% end %>
          <section class="w-100">
            <div class="d-flex justify-content-between align-items-center">
              <h6 style='color: grey'><%= org.name %></h6>
              <% if org.campaigns.count == 0 || org.campaigns.count == 1 %>
                <span class="text-decoration-none badge badge-secondary badge-pill mb-2"><%= "#{org.campaigns.count} campagne" %></span>
             <!--  <#% elsif org.campaigns.count == 1 %>
                <span class="text-decoration-none badge badge-primary badge-pill mb-2"><%= "#{org.campaigns.count} campagne" %></span> -->
              <% else %>
                <span class="text-decoration-none badge badge-primary badge-pill mb-2"><%= "#{org.campaigns.count} campagnes" %></span>
              <% end %>
            </div>
            <small class='mt-1 p-0 d-block max-w-160 text-truncate'><%= org.address %></small>

          </section>
        </div>
      <% end %>
    <% end %>
   <% else %>

    <div class="card pb-0">
       <div class="card-body pt-2 pb-0">
         <div class="d-flex">
            <h6 class="flex-grow-1">Organisations</h6>
            <%= link_to new_organisation_path, class: 'mr-1' do %>
               <i class="fas fa-plus"></i>
            <% end %>
         </div>
         <p class="">Vous n'avez pas d'organisation. Créez la première ⭐️</p>
       </div>
    </div>

  <% end %>

  <!-- only for admin users -->
  <% if policy(User).index? %>
    <h4 class="mt-5">Admin</h4>
    <hr class="mb-3">
    <div>
       <%= link_to "Utilisateurs", users_path, class: "btn btn-primary rounded-pill d-block mt-3 plastroc-button plastroc-light-shadow" %>
    </div>
    <%= link_to "Materiaux", materials_path, class: "btn btn-primary rounded-pill d-block mt-3 plastroc-button plastroc-light-shadow" %>
    <%= link_to "Organisations", organisations_path, class: "btn btn-primary rounded-pill d-block mt-3 plastroc-button plastroc-light-shadow" %>
    <%= link_to "Home page", root_path, class: "btn btn-primary rounded-pill d-block mt-3 plastroc-button plastroc-light-shadow" %>
  <% end %>
</div>



<!-- nav bar -->
<div class="bottom-nav">
    <div class="d-flex justify-content-between">
      <%= link_to missions_path, class: 'text-decoration-none flex-fill' do %>
        <p class=""><i class="fas fa-home"></i></p>
      <% end %>
      <%= link_to campaigns_path, class: 'text-decoration-none flex-fill' do %>
        <p class=""><i class="fas fa-search"></i></p>
      <% end %>
      <%= link_to user_path(current_user), class: 'text-decoration-none flex-fill' do %>
        <p class="active-tab"><i class=" fas fa-user"></i></p>
      <% end %>
    </div>
</div>