config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :organisations
  resources :campaigns, only: [ :new, :create ]

  resources :materials do
    resources :instructions, only: [ :create, :new ]
  end

  resources :campaigns, only: [ :index, :show, :edit, :update ] do
    resources :questions, only: [ :create ]
    resources :package, only: :create do
      resources :missions, only: [ :new, :create ]
    end
    collection do
      get :my_campaigns
    end
    member do
      get :dashboard
      patch :publish
      patch :pause
      patch :finish
      get :duplicate
    end
  end

  resources :questions, only: [ :update, :destroy ] do
    member do
      patch :seen
    end
  end

  resources :instructions, only: [ :edit, :destroy, :update ]
  resources :users, only: [ :index, :show ]
  resources :missions, only: [ :index, :show, :update ] do
    collection do
      get :my_missions
    end
  end
end

app/views/shared/_contact_content.html.erb
<div class="card mt-3">
  <div class="card-body">
    <section>
      <h6>Que faisons nous ?</h6>
      <p><%= @campaign.organisation.about %></p>
    </section>
  </div>
</div>
<div class="card mt-3">
  <div class="card-body">
    <section>
      <h6><span class="icon address">Notre Adresse</h6></span>
      <p><%= @campaign.organisation.address %></p>
    </section>
  </div>
</div>
<div class="card mt-3">
  <div class="card-body">
    <section>
      <h6><span class="icon clock">Horaires d'ouverture</h6></span>
      <p><%= @campaign.organisation.opening_hours %></p>
    </section>
  </div>
</div>
<div class="card mt-3">
  <div class="card-body">
    <section>
      <h6><span class="icon mail">Contact</h6></span>
      <p><%= @campaign.organisation.contact %></p>
    </section>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_how_to_content.html.erb
<H6 class="text-center"><%= @campaign.material.name %></H6>
<p class="text-center"><%= @campaign.material.description %></p>

<% @campaign.sort_by_step_order.each do |instruction| %>
  <div class="card card-m mt-3">
    <% if instruction.media.attached? %>
      <%= cl_image_tag instruction.media.key, height: 500, crop: :fill %>
    <% else %>
      <img src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
    <% end %>

        <div class="card-body">
            <span class="badge badge-pill badge-success">Etape <%= instruction.step_order %></span>
            <section>
                <h6><%= instruction.title %></h6>
                <p><%= instruction.rich_content %></p>
            </section>
        </div>
    </div>
<% end %>

app/views/shared/_info_content.html.erb
<div class="card">
   <div class="card-body pt-3 pb-1">
      <h6 class="text-center text-secondary">Infos</h6>
      <div class="d-flex justify-content-around">
         <div style="max-width: 100px" class="d-flex flex-column align-items-center">
            <%= image_tag "picto-plastics.png", class: "m-2", style: "object-fit:cover; height: 30px"%>
            <p class="w-100 mb-2 text-truncate"><%= @campaign.material.name %></p>
         </div>

         <div class="d-flex flex-column align-items-center">
            <%= image_tag "picto-agenda.png", class: "m-2", style: "object-fit:cover; height: 30px"%>

            <% if (@campaign.number_of_days) > 1 %>
               <p><%= (@campaign.number_of_days) %> jours</p>
            <% elsif (@campaign.number_of_days) == 1 %>
               <p>1 jour</p>
            <% else %>
               <p>Terminée</p>
            <% end %>
         </div>

         <div class="d-flex flex-column align-items-center">
            <%= image_tag "picto-laurel.png", class: "m-2", style: "object-fit:cover; height: 30px"%>
            <p>Level: 1</p> <!-- turn it dynamic when possible -->
         </div>
      </div>
   </div>
</div>

<h5 class="mt-3">Détails</h5>
<p><%= @campaign.description %></p>

<h5>Participants</h5>
<div class="d-flex">
  <% if @campaign.members.empty? %>
    <p>Pas encore de membre. Soyez le premier 😊.</p>
  <% end %>
  <% if @campaign.members.uniq.count > 6 %>
    <% @campaign.members.uniq.first(5).each do |member| %> <%# uniq to avoid showing several times the same pic in case a member has several missions for this campaign %>
      <% if member.photo.attached? %>
        <%= cl_image_tag member.photo.key, height: 40, width: 40, crop: :fill, class: "avatar mx-2"%>
      <% else %>
        <img src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="" class= "avatar mx-2">
      <% end %>
    <% end %>
    <div style='height: 40px; width: 40px; background-color: lightgrey; color: white; border-radius: 50%' class="ml-2 member_counter">
      <p class= 'mt-2 mb-2 text-center font-weight-bold'>+<%= @campaign.members.uniq.count - 5 %></p>
    </div>
  <% else %>
    <% @campaign.members.uniq.each do |member| %> <%# uniq to avoid showing several times the same pic in case a member has several missions for this campaign %>
      <% if member.photo.attached? %>
        <%= cl_image_tag member.photo.key, height: 40, width: 40, crop: :fill, class: "avatar mx-2"%>
      <% else %>
        <img src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="" class= "avatar mx-2">
      <% end %>
    <% end %>
  <% end %>

</div>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_mobile_navbar.html.erb
<div class="bottom-nav">
    <div class="d-flex justify-content-between">
      <%= link_to missions_path, class: 'text-decoration-none flex-fill' do %>
        <p class="<?=(site_url('/missions(.:format)')==$current_url)?'active-tab':''?>"><i class="fas fa-home"></i></p>
      <% end %>
      <%= link_to campaigns_path, class: 'text-decoration-none flex-fill' do %>
        <p class="<?=(site_url('/campaigns(.:format)')==$current_url)?'active-tab':''?>"><i class="fas fa-search"></i></p>
      <% end %>
      <% if current_user %>
        <%= link_to user_path(current_user), class: 'text-decoration-none flex-fill' do %>
            <p class="<?=(site_url('/users/:id(.:format)')==$current_url)?'active-tab':''?>"><i class=" fas fa-user"></i></p>
         <% end %>
      <% end %>
    </div>
</div>


<!--     <div class="bottom-nav">
        <div class="d-flex justify-content-around">
            <p class="active-tab"><i class="fas fa-home"></i></p>
            <p><i class="fas fa-search"></i></p>
            <p><i class="fas fa-user"></i></p>
        </div>
    </div> -->

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if policy(Organisation).create? %>
            <%= link_to "Add Organisation", new_organisation_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if policy(Material).index? %>
            <%= link_to "All materials", materials_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_pop_party.html.erb
<!-- Animation -->
<div class="cannon">
  <div class="cannon__path cannon__path--sm cannon__path--angle-2">
    <div class="cannon__confetti cannon__confetti--flake cannon__confetti--color-3"></div>
    <div class="cannon__confetti cannon__confetti--ribbon cannon__confetti--color-1"></div>
    <div class="cannon__confetti cannon__confetti--ribbon cannon__confetti--color-2"></div>
    <div class="cannon__confetti cannon__confetti--flake cannon__confetti--color-1"></div>
    <div class="cannon__confetti-spacer"></div>
  </div>
  <div class="cannon__path cannon__path--md cannon__path--angle-1">
    <div class="cannon__confetti cannon__confetti--ribbon cannon__confetti--color-2"></div>
    <div class="cannon__confetti cannon__confetti--flake cannon__confetti--color-2"></div>
    <div class="cannon__confetti cannon__confetti--flake cannon__confetti--color-3"></div>
    <div class="cannon__confetti cannon__confetti--ribbon cannon__confetti--color-1"></div>
    <div class="cannon__confetti cannon__confetti--flake cannon__confetti--color-4"></div>
    <div class="cannon__confetti-spacer"></div>
  </div>
  <div class="cannon__path cannon__path--lg cannon__path--angle0">
    <div class="cannon__confetti cannon__confetti--ribbon cannon__confetti--color-1"></div>
    <div class="cannon__confetti cannon__confetti--ribbon cannon__confetti--color-4"></div>
    <div class="cannon__confetti cannon__confetti--ribbon cannon__confetti--color-2"></div>
    <div class="cannon__confetti cannon__confetti--flake cannon__confetti--color-3"></div>
    <div class="cannon__confetti-spacer"></div>
  </div>
  <div class="cannon__path cannon__path--md cannon__path--angle1">
    <div class="cannon__confetti cannon__confetti--flake cannon__confetti--color-3"></div>
    <div class="cannon__confetti cannon__confetti--ribbon cannon__confetti--color-1"></div>
    <div class="cannon__confetti cannon__confetti--ribbon cannon__confetti--color-4"></div>
    <div class="cannon__confetti cannon__confetti--flake cannon__confetti--color-3"></div>
    <div class="cannon__confetti cannon__confetti--ribbon cannon__confetti--color-2"></div>
    <div class="cannon__confetti-spacer"></div>
  </div>
  <div class="cannon__path cannon__path--sm cannon__path--angle2">
    <div class="cannon__confetti cannon__confetti--ribbon cannon__confetti--color-2"></div>
    <div class="cannon__confetti cannon__confetti--flake cannon__confetti--color-3"></div>
    <div class="cannon__confetti cannon__confetti--flake cannon__confetti--color-4"></div>
    <div class="cannon__confetti cannon__confetti--ribbon cannon__confetti--color-1"></div>
    <div class="cannon__confetti-spacer"></div>
  </div>

app/views/shared/_questions_display.html.erb
<% if current_user != @campaign.user %>
  <!-- Pour tous les users -->
  <h5 class="mt-2" id="question_title">Questions</h5>
  <button href="#" class='btn btn-outline-primary rounded-pill d-block mt-3 plastroc-outline-button w-100' data-toggle="modal" data-target="#NewQuestion">
    Ajouter une question
  </button>
  <% @campaign.questions.order(:created_at).reverse.each do |question|%>
    <blockquote class="blockquote card mt-3" id="questiontitle-<%= question.id %>">
       <div class="card-body">
          <div class="col-11">
            <h6 class="mb-0"><%= question.title %></h6>
            <p class="mb-0"><%= question.content %></p>
            <footer class="blockquote-footer mt-2 mb-0"><%= question.created_at.strftime("le %m/%d/%Y") %><cite title="Source Title"> par <%= question.user.first_name %></cite></footer>
          </div>
          <div class="col-12 mt-3">
            <% if question.answer.nil? %>
              <p class="text-right p-0 m-0">
                <a class="btn btn-sm btn-link-secondary rounded-pill" >🤨 Pas encore de réponse</a>
              </p>
            <% else %>
              <p class="text-right p-0 m-0">
                <a class="btn btn-sm btn-link-secondary rounded-pill" data-toggle="collapse" href="#question-<%= question.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">📣 Répondu <%= question.updated_at.strftime("le %m/%d/%Y") %> <i class="fas fa-chevron-down"></i></a>
              </p>
               <div class="collapse" id="question-<%= question.id %>">
                  <blockquote class="blockquote">
                     <p class="mb-0 mt-2 text-right"><%= question.answer %></p>
                     <footer class="blockquote-footer mt-2 mb-0 text-right"><%= question.campaign.organisation.user.first_name %> de <%= question.campaign.organisation.name %></footer>
               </div>
             <% end %>
          </div>
       </div>
    </blockquote>
  <% end %>
<% else %>
  <!-- Pour tous les owners -->
  <h5 id="question_title">Questions</h5>
  <% if @campaign.questions.empty? %>
  <p>Pas encore de questions 😅</p>
  <% else %>
  <% @campaign.questions.order(:created_at).reverse.each do |question|%>
      <blockquote class="blockquote card mt-3" id="questiontitle-<%= question.id %>">
         <div class="card-body">
            <div class="col-11">
              <h6 class="mb-0"><%= question.title %></h6>
              <p class="mb-0"><%= question.content %></p>
              <footer class="blockquote-footer mt-2 mb-0"><%= question.created_at.strftime("le %m/%d/%Y") %><cite title="Source Title"> par <%= question.user.first_name %></cite></footer>
            </div>
            <div class="col-12 mt-3">
              <% if question.answer %>
                <p class="text-right p-0 m-0">
                  <a class="btn btn-sm btn-link-secondary rounded-pill " data-toggle="collapse" href="#question-<%= question.id %>" role="button" aria-expanded="false" aria-controls="collapseExample">📣 Répondu <%= question.updated_at.strftime("le %m/%d/%Y") %> <i class="fas fa-chevron-down"></i></a>
                </p>
                 <div class="collapse" id="question-<%= question.id %>">
                    <blockquote class="blockquote">
                      <p class="mb-0 mt-2 text-right"><%= question.answer %></p>
                      <footer class="blockquote-footer mt-2 mb-0 text-right"><%= question.campaign.organisation.user.first_name %> de <%= question.campaign.organisation.name %></footer>
                      <div class='d-flex justify-content-end mt-1'>
                        <%= link_to question_path(question), method: :delete, class: 'btn btn-outline-danger rounded-pill d-block plastroc-outline-button mr-3' do %>
                          <i class="fas fa-trash-alt"></i>
                        <% end %>
                        <button href="#" class='btn btn-primary flex-grow-1 rounded-pill plastroc-button' data-toggle="modal" data-target="#answer-<%= question.id %>">
                          Modifier <i class="fas fa-pen"></i>
                        </button>
                      </div>
                 </div>
              <% else %>
                <div class='d-flex justify-content-end'>
                  <%= link_to question_path(question), method: :delete, class: 'btn btn-outline-danger rounded-pill d-block plastroc-outline-button mr-3' do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                  <button href="#" class='btn btn-primary flex-grow-1 rounded-pill plastroc-button' data-toggle="modal" data-target="#answer-<%= question.id %>">
                    Répondre <i class="pl-2 fas fa-reply"></i>
                  </button>
                </div>
               <% end %>
            </div>
         </div>
      </blockquote>
      <!-- Question Edit Modal to give answer-->
      <div class="modal fade" id="answer-<%= question.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Répondre à la question</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <%= simple_form_for(question, remote: true) do |f| %>
                <%= f.input :answer,
                        label: false,
                        placeholder: "Réponse*",
                        input_html: { class: "col-12 mb-3 h100" } %>
                    <%= button_tag type: 'submit', class: "btn col-12 btn-primary rounded-pill plastroc-button" do %>
                      <i class="fas fa-paper-plane"></i>
                    <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <!-- End of Question Edit Modal to give answer-->
    <% end %>
  <% end %>
<% end %>

app/views/shared/_wagon_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <% if policy(Organisation).index? %>
            <%= link_to "Organisations", organisations_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if policy(Organisation).create? %>
            <%= link_to "✚ Organisation", new_organisation_path, class: "nav-link" %>
          <% end %>
        </li>
          <% if policy(Campaign).my_campaigns? %>
            <%= link_to "Campagnes", my_campaigns_campaigns_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if policy(Campaign).create? %>
            <%= link_to "✚ Campagne", organisations_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if policy(Material).index? %>
            <%= link_to "Matériaux", materials_path, class: "nav-link" %>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>