config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :organisations
  resources :campaigns, only: [ :new, :create ]

  resources :materials do
    resources :instructions, only: [ :create, :new ]
  end

  resources :campaigns, only: [ :index, :show, :edit, :update ] do
    resources :questions, only: [ :create ]
    resources :package, only: :create do
      resources :missions, only: [ :new, :create ]
    end
    collection do
      get :my_campaigns
    end
    member do
      get :dashboard
      patch :publish
      patch :pause
      patch :finish
      get :duplicate
    end
  end

  resources :questions, only: [ :update, :destroy ] do
    member do
      patch :seen
    end
  end

  resources :instructions, only: [ :edit, :destroy, :update ]
  resources :users, only: [ :index, :show ]
  resources :missions, only: [ :index, :show, :update ] do
    collection do
      get :my_missions
    end
  end
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  attr_accessor :material_category

  belongs_to :organisation
  belongs_to :material
  has_many :packages, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :missions, through: :packages
  has_one :user, through: :organisation
  has_one_attached :photo

  scope :ongoing, -> { where(status: 'ongoing') }

  UNITS = ['g', 'kg', 'l', 'unité']

  validates :name, presence: true, length: { maximum: 26 }
  validates :description, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  # validates :published, presence: true
  validates :target, presence: true, numericality: { only_integer: true }
  validates :unit, presence: true, inclusion: { in: UNITS }

  # Utilities

  scope :ongoing, -> { where(status: 'ongoing') }
  scope :done, -> { where(status: 'done') }
  scope :paused, -> { where(status: 'paused') }


  def number_of_days
    (end_date - Date.today).to_i
  end

  def sort_by_step_order
    material.instructions.order(step_order: :asc)
  end

  def members
    missions.map { |mission| mission.user }
  end
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController

  def index # for the moment show all campaigns but will need to sort if on organisation view
    @categories = active_materials_categories
    if params[:category] && params[:category].keys.any?
    # if params[:category_filter]&.split(',')&.any?  params[:category_filter].split(',')
      @campaigns = policy_scope(Campaign).where(status: 'ongoing').includes(:material).where(materials: { category: params[:category].keys })
      @organisations = @campaigns.map { |campaign| campaign.organisation }
      @markers = create_markers(@organisations)
      # redirect_to campaigns_path
    else
      @campaigns = policy_scope(Campaign).where(status: 'ongoing')
      @organisations = organisations_with_active_campaigns
      @markers = create_markers(@organisations)
    end
    # respond_to do |format|
    #   format.html
    #   format.json { @campaings.to_json }
    # end
  end

  def my_campaigns
    @ongoing_campaigns = current_user.campaigns.ongoing
    @done_campaigns = current_user.campaigns.done
    @paused_campaigns = current_user.campaigns.paused
    @questions = current_user.questions.where(seen: false)
    authorize Campaign
  end

  def show
    @campaign = Campaign.find(params[:id])
    @packages = @campaign.packages
    @mission = Mission.new
    @question = Question.new
    @volume_done = done_missions_calcul
    @ratio = @volume_done.fdiv(@campaign.target) * 100 # used in dataset for animated bar
    @citation = Citation.all.sample
    @sorter_campaigns = current_user.missions.ongoing.map { |mission| mission.package.campaign }
    authorize @campaign
  end

  def new
    @campaign = Campaign.new
    @materials = Material.all.select(:id, :name, :category).group_by(&:category)
    authorize @campaign
  end

  def create
    @campaign = Campaign.new(campaign_params)
    authorize @campaign
    @campaign.published = true
    @campaign.status = "ongoing"
    if @campaign.save
      # => Crétation automatique des packages
      create_packages
      flash[:alert] = 'campagne ajoutée'
      redirect_to dashboard_campaign_path(@campaign) #redirect to campaign show
    else
      render :new
    end
  end

  def duplicate
    campaign_to_dupilcate = Campaign.find(params[:id])
    @campaign = campaign_to_dupilcate.dup
    authorize @campaign
    @campaign.start_date = Date.today
    @campaign.end_date = Date.today + 10
    @campaign.published = true
    @campaign.status = "ongoing"
    @campaign.save
    # => Crétation automatique des packages
    create_packages
    flash[:alert] = 'campagne dupliquée'
    redirect_to edit_campaign_path(@campaign) #redirect to edit
  end

  def edit
    @campaign = Campaign.find(params[:id])
    authorize @campaign
  end

  def update
    @campaign = Campaign.find(params[:id])
    @campaign.update(campaign_params)
    authorize @campaign
    if @campaign.save
      flash[:notice] = "campagne mise à jour"
      redirect_to dashboard_campaign_path(@campaign)
    else
      render :edit
    end
  end


  def dashboard
    @campaign = Campaign.find(params[:id])
    @ongoing_missions = @campaign.missions.ongoing
    @volume_done = done_missions_calcul
    @volume_total = total_missions_calcul
    @ratio_done = @volume_done.fdiv(@campaign.target) * 100 # used in dataset for animated bar
    @ratio_engaged = @volume_total.fdiv(@campaign.target) * 100 # used in dataset for animated bar
    authorize @campaign
  end

  def pause
    @campaign = Campaign.find(params[:id])
    authorize @campaign
    @campaign.published = false
    @campaign.status = "paused"
    @campaign.save
    flash[:notice] = "campagne en pause"
    redirect_to dashboard_campaign_path(@campaign)
  end

  def finish
    @campaign = Campaign.find(params[:id])
    authorize @campaign
    @campaign.update(status: "done")
    flash[:notice] = "campagne terminée"
    redirect_to my_campaigns_campaigns_path
  end


  def publish
    @campaign = Campaign.find(params[:id])
    authorize @campaign
    if total_missions_calcul >= @campaign.target
      flash[:notice] = "Vous ne pouvez pas publier sans changer la quantité total"
    else
      @campaign.published = true
      @campaign.status = "ongoing"
      flash[:notice] = "campagne publiée"
    end
    @campaign.save
    redirect_to dashboard_campaign_path(@campaign)
  end

  private

  def active_materials_categories
    categories = []
    Material.all.each do |material|
      if !material.campaigns.empty?
        categories << material.category
      end
    end
    return categories.uniq
  end

  def organisations_with_active_campaigns
    Organisation.joins(:campaigns).where(campaigns: { status: 'ongoing' })
  end

  def number_of_active_campaign(organisation)
    Campaign.where(organisation: organisation).where(status: 'ongoing').count
  end

  def active_campaigns(organisation)
    Campaign.where(organisation: organisation).where(status: 'ongoing')
  end

  def create_packages
    iterators = [(@campaign.target / @campaign.min_package).floor, 4].min
    names = ['Corail', 'Tortue', 'Dauphin', 'Baleine']
    x = 0
    iterators.times do
      @name = names[x]
      @quantity = (x + 1) * @campaign.min_package
      @reward = (x + 1) * @campaign.min_package / 2
      @campaign.packages.create(name: @name, quantity: @quantity, xp_reward: @reward)
      x += 1
    end
  end

  def done_missions_calcul
    missions = @campaign.missions
    volumes_done = missions.done.map { |mission| mission.package.quantity }
    return volumes_done.sum
  end

  def total_missions_calcul
    missions = @campaign.missions
    volumes_total = missions.map { |mission| mission.package.quantity }
    return volumes_total.sum
  end

  def create_markers(organisations)
    @organisations.map do |organisation|
      @organistion_active_campaigns = active_campaigns(organisation)
      url = organisation.photo.attached? ? url_for(organisation.photo) : helpers.asset_url('placeholder.png')
      {
        campaigns_number: number_of_active_campaign(organisation),
        lat: organisation.latitude,
        lng: organisation.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { organisation: organisation }),
        image_url: url,
        id: organisation.id
      }
    end
  end

  def campaign_params
    params.require(:campaign).permit(
      :organisation_id,
      :name,
      :description,
      :start_date,
      :end_date,
      :target,
      :unit,
      :photo,
      :material_id,
      :status,
      :min_package,
      :published)
  end
end

app/views/campaigns/_info_window.html.erb
<h6><%= organisation.name %></h6>
<p><%= organisation.address %></p>
  <ul class="list-group">
  <% @organistion_active_campaigns.each do |campaign| %>
    <% if campaign.user == current_user %>
      <%= link_to dashboard_campaign_path(campaign), class: 'text-decoration-none', style: 'outline: none' do %>
        <li style="outline: none" class="pt-1 pb-1 pl-2 pr-2 list-group-item d-flex justify-content-between align-items-center rounded-pill mb-1">
          <p class="p-0 mb-0 text-left col-9 text-truncate"><%= campaign.name %></p>
          <span class="col-3 badge badge-primary badge-pill text-truncate"><%= campaign.material.name %></span>
        </li>
      <% end %>
    <% else %>
      <%= link_to campaign_path(campaign), class: 'text-decoration-none', style: 'outline: none' do %>
        <li style="outline: none" class="pt-1 pb-1 pl-2 pr-2 list-group-item d-flex justify-content-between align-items-center rounded-pill mb-1">
          <p class="p-0 mb-0 text-left col-9 text-truncate"><%= campaign.name %></p>
          <span class="col-3 badge badge-primary badge-pill text-truncate"><%= campaign.material.name %></span>
        </li>
      <% end %>
    <% end %>
  <% end %>
</ul>

app/views/campaigns/dashboard.html.erb
<!-- Banner -->

<div class="banner d-flex flex-column justify-content-between"

style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),
                          <% if @campaign.photo.attached? %>
                            url('<%= cl_image_path @campaign.photo.key, height: 500, crop: :fill %>')"
                          <% else %>
                            url('https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80')"
                          <% end %>>
  <div class="container">
    <!-- add if statement depending on sorter or recycler -->
    <h4><%= link_to missions_path, class: "position-absolute" do %>
      <i class="fas fa-arrow-left"></i>
      <% end %>
    </h4>
  </div>

  <div class="container">
    <div class="d-flex flex-column align-items-center">
      <% if @campaign.organisation.photo.attached? %>
        <%= cl_image_tag @campaign.organisation.photo.key, width: 56, height: 56, crop: :fill, class: "avatar-large mb-2 plastroc-light-shadow"%>
      <% else %>
        <img style='height: 56px; width: 56px', class='avatar-large mb-2 plastroc-light-shadow' src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
      <% end %>
      <h5 class="mb-0"><%= @campaign.name %></h5>
      <h6>by <%= @campaign.organisation.name %></h6>
    </div>
  </div>
</div>

<!-- Tabs -->

<nav class="nav plastroc-tabs d-flex justify-content-around flex-nowrap py-3">
  <a class="active" href="#tab-dashboard" data-toggle="tab">Dashboard</a>
  <a class="" href="#tab-mission-details" data-toggle="tab">Campagne</a>
  <a class="" href="#tab-about-me" data-toggle="tab">Infos</a>
</nav>

<!-- Tabs-content -->

<div class="tab-content position-relative" style="margin-bottom: 75px;">

  <!-- Dashboard-Tab -->

  <div class="tab-pane active" id="tab-dashboard">
    <div class="container">
      <div class="d-flex align-items-center">
        <h5 class="mt-2 mr-2">Progression</h5>
        <% if @campaign.status == "ongoing" %>
          <span class="text-decoration-none badge badge-primary badge-pill mb-0"><%= "#{@campaign.status}" %></span>
        <% else %>
          <span class="text-decoration-none badge badge-dark badge-pill mb-0"><%= "#{@campaign.status}" %></span>
        <% end %>
      </div>
      <!-- Engagement des membres -->
      <div class="d-flex justify-content-between align-items-center">
          <p class="mb-0"><strong>Engagé</strong></p>
          <p class="mb-0" id="volume_engaged" data-total='<%= @ratio_engaged %>'><%= @volume_total %>/<%= @campaign.target %><%= @campaign.unit == "unité" ? "unités" : @campaign.unit %></p>
      </div>
       <div class="plastroc-progress-bar mt-2 mb-4">
        <% if @volume_total == 0 %>
          <p class='m-2'>🤔 Pas encore de mission commencée</p>
        <% else %>
          <div class="rounded-pill plastroc-bg-primary-gradient" id="myEngagedBar">...</div>
        <% end %>
       </div>

       <!-- Completion par les membres -->
       <div class="d-flex justify-content-between align-items-center">
          <p class="mb-0"><strong>Complété</strong></p>
          <p class="mb-0" id="volume_done" data-total='<%= @ratio_done %>'><%= @volume_done %>/<%= @campaign.target %><%= @campaign.unit == "unité" ? "unités" : @campaign.unit %></p>
      </div>
       <div class="plastroc-progress-bar mt-2 mb-4">
        <% if @volume_done == 0 %>
          <p class='m-2'>☺️ Pas encore de mission terminée</p>
        <% else %>
          <div class="rounded-pill plastroc-bg-primary-gradient" id="myDoneBar"></div>
        <% end %>
       </div>

      <!-- cf new show for dynamic progress bar -->
      <div class="plastroc-progress-bar mt-2 mb-4">
        <div class="rounded-pill plastroc-bg-primary-gradient"></div>
      </div>

      <!-- Bouton Missions en cours -->
      <p class="text-center">Liste des missions en cours pour validation</p>
      <button type="button" class="col-6 offset-3 btn btn-primary rounded-pill d-block mb-3 plastroc-button plastroc-light-shadow" data-toggle="modal" data-target="#missions">
        <%= @ongoing_missions.count %> en cours
      </button>

      <%= link_to duplicate_campaign_path(@campaign), class: "col-6 offset-3 btn btn-outline-primary rounded-pill d-block mb-3 plastroc-outline-button plastroc-light-shadow" do %>
        <i class="far fa-copy"></i> Dupliquer
      <% end %>
      <!-- Modal missions en cours -->
      <div class="modal fade" id="missions" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Missions en cours</h5>
            </div>
            <div class="modal-body">
              <p class="text-center">Donnez le <span class="badge badge-info badge-pill">code</span> au trieur à la dépose pour validation de la mission:</p>
              <% if @ongoing_missions.empty? %>
                <p class="text-center">Pas de mission en cours pour le moment 🤨.</p>
              <% else %>
                <ul class="list-group">
                  <% @ongoing_missions.each do |mission| %>
                    <li class="list-group-item d-flex justify-content-between align-items-center">
                      <%= mission.user.first_name %> <%= mission.user.last_name[0] %>
                      <div class='d-flex'>
                        <span class="badge badge-primary badge-pill"><i class="fas fa-weight-hanging"></i> <%= mission.package.quantity %> <%= mission.package.campaign.unit %></span>
                        <span class="badge badge-info badge-pill ml-1"><%= mission.package.campaign.id %><%= mission.id %></span>
                      </div>
                    </li>
                  <% end %>
                </ul>
              <% end %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-primary rounded-pill" data-dismiss="modal">Close</button>
            </div>
          </div>
        </div>
      </div>

      <%= render 'shared/questions_display' %>

    </div>
  </div>

  <!-- Mission-details-Tab -->

  <div class="tab-pane" id="tab-mission-details">
    <div class="container">

      <%= render 'shared/info_content' %>

      <h5>Tuto</h5>

      <%= render 'shared/how_to_content' %>

    </div>
  </div>

  <!-- About-me-Tab -->

  <div class="tab-pane" id="tab-about-me">
    <div class="container">

      <%= render 'shared/contact_content' %>

    <% if current_user != @campaign.user %>
      <button href="#" class='btn btn-outline-primary rounded-pill d-block mt-3 plastroc-outline-button w-100'>
        Poser une question
      </button>
    <% end %>

    </div>
  </div>

<!-- Edit & stop buttons -->

  <% if @campaign.status == "done" %>
    <div id="bottom-nav-disabled">
      <p class= "plastroc-button-sticky-bottom d-block py-3">Campagne Terminée 🎉</p>
    </div>
  <% else %>
    <div class="bottom-nav">
        <div class="d-flex justify-content-around">
            <p><a href="#" style="color: &plastroc-main;" data-toggle="modal" data-target="#editModal">Editer</a></p>
            <% if @campaign.status == "ongoing" %>
              <p><%= link_to "Stopper", pause_campaign_path(@campaign), method: :patch, style: "color: red", remote: true %></p>
            <% else %>
              <button data-id="<%= @campaign.id %>" class="finish-campaign">Terminer</button>
      <%= link_to "",
                  finish_campaign_path(@campaign),
                  method: :patch,
                  # data: { confirm: "Are you sure?" },
                  class: 'hidden',
                  id: "fin-camp-#{@campaign.id}" %>
              <p><%= link_to "Reprendre", publish_campaign_path(@campaign), method: :patch, remote: true %></p>
            <% end %>
        </div>
    </div>

  <% end %>


</div>

<!-- Modal Edit  -->

<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Editer la campagne</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="container" style="margin-bottom: 75px;">
          <div id="materials" data-materials="<%= @materials.to_json %>"></div>
          <%= simple_form_for @campaign do |f| %>
            <%= f.input :name,
                        label: "Nom",
                        placeholder: "Nom*",
                        input_html: { class: "col-12 mb-3" } %>

            <%= f.input :description,
                        label: "Description",
                        placeholder: "Description*",
                        input_html: { class: "col-12 mb-3" } %>

            <div class="form-row mb-3">
              <div class="d-flex">
                <div class="mr-1">
                  <%= f.input :start_date,
                              label: "Date de début",
                              placeholder: "jj/mm/aaaa",
                              as: :string,
                              required: false,
                              input_html: { class: "date-picker" } %>
                </div>

                <div class="ml-1">
                  <%= f.input :end_date,
                              label: "Date de fin",
                              placeholder: "jj/mm/aaaa",
                              as: :string,
                              required: false,
                              input_html: { class: "date-picker", id: "secondRangeInput" } %>
                </div>
              </div>
            </div>

            <div class="form-row mb-3">
              <div class="d-flex">
                <div class="mr-2">
                  <%= f.input :target,
                              label: "Quantité souhaitée",
                              placeholder: "500",
                              input_html: { min: '0', class: "input" } %>
                </div>
                <%= f.input :min_package,
                            label: "Minimum par trieur",
                            input_html: { min: '0', class: "input" } %>
              </div>
            </div>

            <%= f.input :unit,
                        label: false,
                        as: :radio_buttons,
                        collection: Campaign::UNITS,
                        boolean_style: :inline,
                        collection_wrapper_tag: 'div',
                        collection_wrapper_class: 'flex-nowrap d-flex',
                        item_wrapper_class: 'unit-item flex-grow-1 align-self-stretch',
                        input_html: {class: 'unit-selector'} %>

            <%= f.input :photo,
                    as: :file,
                    input_html: { class: "d-none", id: 'photo-input' },
                    label_html: { class: 'upload-photo col-12 text-center'},
                    label: '📷 Choisissez une photo' %>
            <%= image_tag "", width: 300, class: "hidden mx-auto mb-2", id: "photo-preview" %>

            <%= f.submit 'Valider', class: "mt-2 btn btn-primary rounded-pill d-block plastroc-button plastroc-light-shadow col-12 mb-3" %>
          <% end %>
          <%= link_to 'Annuler', dashboard_campaign_path(@campaign), class: "btn btn-outline-danger rounded-pill d-block mt-3 plastroc-outline-button" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/edit.html.erb
<div class="container" style="margin-bottom: 75px;">
  <div id="materials" data-materials="<%= @materials.to_json %>"></div>
  <h4 class="mt-3">Editer Campagne</h4>
  <%= simple_form_for [@organisation, @campaign] do |f| %>
    <%= f.input :name,
                label: false,
                placeholder: "Nom*",
                input_html: { class: "col-12 mb-3" } %>

    <%= f.input :description,
                label: false,
                placeholder: "Description*",
                input_html: { class: "col-12 mb-3" } %>

        <div class="form-row mb-3">
          <div class="d-flex">
            <div class="mr-1">
              <%= f.input :start_date,
                          label: "Date de début",
                          placeholder: "jj/mm/aaaa",
                          as: :string,
                          required: false,
                          input_html: { class: "date-picker" } %>
            </div>

            <div class="ml-1">
              <%= f.input :end_date,
                          label: "Date de fin",
                          placeholder: "jj/mm/aaaa",
                          as: :string,
                          required: false,
                          input_html: { class: "date-picker", id: "secondRangeInput" } %>
            </div>
          </div>
        </div>

        <div class="form-row mb-3">
          <div class="d-flex">
            <div class="mr-2">
              <%= f.input :target,
                          label: "Quantité souhaitée",
                          placeholder: "500",
                          input_html: { min: '0', class: "input" } %>
            </div>
            <%= f.input :min_package,
                        label: "Minimum par trieur",
                        input_html: { min: '0', class: "input" } %>
          </div>
        </div>

    <%= f.input :unit,
                label: false,
                as: :radio_buttons,
                collection: Campaign::UNITS,
                boolean_style: :inline,
                collection_wrapper_tag: 'div',
                collection_wrapper_class: 'flex-nowrap d-flex',
                item_wrapper_class: 'unit-item flex-grow-1 align-self-stretch',
                input_html: {class: 'unit-selector'} %>

    <%= f.input :photo,
                    as: :file,
                    input_html: { class: "d-none", id: 'photo-input' },
                    label_html: { class: 'upload-photo col-12 text-center'},
                    label: '📷 Choisissez une photo' %>
    <%= image_tag "", width: 300, class: "hidden mx-auto mb-2", id: "photo-preview" %>

    <%= f.submit 'Valider', class: "mt-2 btn btn-primary rounded-pill d-block plastroc-button plastroc-light-shadow col-12 mb-3" %>
  <% end %>
  <%= link_to 'Annuler', dashboard_campaign_path(@campaign), class: "btn btn-outline-primary rounded-pill d-block mt-3 plastroc-outline-button" %>
</div>

app/views/campaigns/index.html.erb
<div class="d-flex flex-column min-vh-100" style="padding-bottom: 60px;">
   <div class="map-container flex-grow-1" style="height: 65vh;">
      <div id="map" style="width: 100%; height: 100%;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      <div class="map-transition">
        <div class="d-flex justify-content-center">
          <%= form_tag campaigns_path, method: :get, class: "filter_search", id: "filter-form" do %>
            <% @categories.each do |category| %>
              <%= check_box_tag "category[#{category}]", category, params[:category]&.include?(category) %>
              <%= label_tag "category[#{category}]", category, style: '', class: "rounded-pill px-2" %>
            <% end %>
            <%= submit_tag "Apply filters", class: 'btn btn-primary d-none', id: "filter-form-button" %>
          <% end %>
        </div>
      </div>
   </div>
<!-- nav bar -->
<div class="bottom-nav">
   <div class="d-flex justify-content-between">
      <%= link_to missions_path, class: 'text-decoration-none flex-fill' do %>
         <p class=""><i class="fas fa-home"></i></p>
      <% end %>
      <%= link_to campaigns_path, class: 'text-decoration-none flex-fill' do %>
         <p class="active-tab"><i class="fas fa-search"></i></p>
      <% end %>
      <%= link_to user_path(current_user), class: 'text-decoration-none flex-fill' do %>
         <p class=""><i class=" fas fa-user"></i></p>
      <% end %>
   </div>
</div>
<div>

<!-- , onchange: "this.form.submit(); this.disabled = false;" -->

   <h4 class="text-center page-title">Missions</h4>
   <div class="campaigns-wrapper">
      <% @campaigns.each do |campaign| %>
         <div class="col-11 col-md-4 mt-3" id="campaign-<%= campaign.organisation.id %>">
            <% if campaign.user == current_user %>
               <%= link_to dashboard_campaign_path(campaign),class: 'text-decoration-none' do %>
                  <div class="card campaign-card" data-organisation-id="<%= campaign.organisation.id %>">
                     <div class="card-horizontal">
                        <div class="img-square-wrapper campaign-card-img">
                           <% if campaign.photo.attached? %>
                              <%= cl_image_tag campaign.photo.key, height: 100, width: 100, crop: :fill %>
                           <% else %>
                              <img style="height: 100px; width: 100px; object-fit: cover" src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
                           <% end %>
                        </div>
                        <div class="card-content-s p-3 d-flex flex-column justify-content-between align-items-start">
                          <div class="m-0 d-flex w-100">
                            <span class="max-w-160 badge badge-primary rounded-pill mb-1 d-inline-block text-truncate"><%= campaign.material.name %></span>
                          </div>
                          <h6 class="max-w-160 mb-0 text-truncate"><%= campaign.organisation.name %></h6>
                          <small class='mt-1 max-w-160 p-0 text-truncate'><%= campaign.name %></small>
                        </div>
                     </div>
                  </div>
               <% end %>
            <% else %>
               <%= link_to campaign_path(campaign),class: 'text-decoration-none' do %>
                  <div class="card campaign-card" data-organisation-id="<%= campaign.organisation.id %>">
                     <div class="card-horizontal">
                        <div class="img-square-wrapper campaign-card-img">
                           <% if campaign.photo.attached? %>
                              <%= cl_image_tag campaign.photo.key, height: 100, width: 100, crop: :fill %>
                           <% else %>
                              <img style="height: 100px; width: 100px; object-fit: cover" src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
                           <% end %>
                        </div>
                        <div class="card-content-s p-3 d-flex flex-column justify-content-between align-items-start">
                          <div class="m-0 d-flex w-100">
                            <span class="max-w-160 badge badge-primary rounded-pill mb-1 d-inline-block text-truncate"><%= campaign.material.name %></span>
                          </div>
                          <h6 class="max-w-160 mb-0 text-truncate"><%= campaign.organisation.name %></h6>
                          <small class='mt-1 max-w-160 p-0 text-truncate'><%= campaign.name %></small>
                        </div>
                     </div>
                  </div>
               <% end %>
            <% end %>
         </div>
      <% end %>
   </div>
</div>