config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :organisations
  resources :campaigns, only: [ :new, :create ]

  resources :materials do
    resources :instructions, only: [ :create, :new ]
  end

  resources :campaigns, only: [ :index, :show, :edit, :update ] do
    resources :questions, only: [ :create ]
    resources :package, only: :create do
      resources :missions, only: [ :new, :create ]
    end
    collection do
      get :my_campaigns
    end
    member do
      get :dashboard
      patch :publish
      patch :pause
      patch :finish
      get :duplicate
    end
  end

  resources :questions, only: [ :update, :destroy ] do
    member do
      patch :seen
    end
  end

  resources :instructions, only: [ :edit, :destroy, :update ]
  resources :users, only: [ :index, :show ]
  resources :missions, only: [ :index, :show, :update ] do
    collection do
      get :my_missions
    end
  end
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :user
  belongs_to :package
  has_one :campaign, through: :package

  scope :ongoing, -> { where(status: 'ongoing') }
  scope :done, -> { where(status: 'done') }

  def recently_done?
    (DateTime.now.to_i - completed_at.to_i) < 10
  end

  def recently_created?
    (DateTime.now.to_i - created_at.to_i) < 10
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController

  def index
    @missions = policy_scope(Mission).ongoing.first(3)
    @campaigns = current_user.campaigns.first(3)
    @first_mission_done = first_mission_done_achivement?
    @questions = current_user.questions.where(seen: false)
    @top_3 = User.order(xp: :desc).first(3)
  end

  def my_missions
    @ongoing_missions = current_user.missions.ongoing
    @done_missions = current_user.missions.done
    @questions = current_user.questions.where(seen: false)
    authorize Mission
  end

  def show
    @mission = Mission.find(params[:id])
    @package = @mission.package
    @campaign = @package.campaign
    @first_mission_subscription = first_mission_subscription_achivement?
    @question = Question.new
    # calcul of done missions
    missions = @campaign.missions
    missions_done = missions.select { |mission| mission.status == "done" }
    volumes_done = []
    missions_done.each do |mission_done|
      volumes_done << mission_done.package.quantity
    end
    @volume_done = volumes_done.sum
    authorize @mission
  end

  def new
    @mission = Mission.new
    @package = Package.find(params[:package_id])
    @campaign = Campaign.find(params[:campaign_id])
    authorize @mission
  end

  def create
    @mission = Mission.new
    authorize @mission
    @mission.user = current_user
    @package = Package.find(params[:package_id])
    @mission.package = @package
    if @mission.save!
      if total_missions_calcul >= @mission.campaign.target
        @mission.campaign.update(status: "paused", published: false)
      end
      redirect_to mission_path(@mission)
    else
      redirect_to campaign_path(@package.mission)
    end
  end

  def update
    @mission = Mission.find(params[:id])
    authorize @mission
    @mission.update(status: 'done', completed_at: DateTime.now)
    @user = current_user
    if @user.missions[0] == @mission
      @user.xp += @mission.package.xp_reward + 40
    else
      @user.xp += @mission.package.xp_reward
    end
    @user.save
    redirect_to missions_path
  end

  private

  def total_missions_calcul
    missions = @mission.campaign.missions
    volumes_total = missions.map { |mission| mission.package.quantity }
    return volumes_total.sum
  end

  def first_mission_subscription_achivement?
    if current_user.missions != []
      bolean = current_user.missions.count == 1 && current_user.missions.last.recently_created?
    end
    return bolean
  end

  def first_mission_done_achivement?
    if current_user.missions != []
      bolean = current_user.missions.done.count == 1 && current_user.missions.last.recently_done?
    end
    return bolean
  end
end

app/views/missions/index.html.erb
<div class="home-banner" style="background-image: url(<%= image_path('leaf-illus.png') %>);">
   <div class="container">
     <h3 class="text-left py-4">Dashboard</h3>
   </div>
</div>
<div style="margin-bottom: 72px" class='container'>
<!-- My question's answers if any -->
  <% if @questions.count > 0 %>
  <p>
    <button class="card d-block mt-2 w-100 border border-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      <div class="d-flex align-items-center justify-content-center">
        <h4 class="m-0 pr-3">📣</h4>
        <p class="mt-3"><strong><%= @questions.count %> réponse(s) à vos questions</strong></p>
      </div>
    </button>
  </p>
  <div class="collapse" id="collapseExample">
    <div class="card card-body">
      <ul class="list-group">
        <% @questions.each do |question| %>
          <%= link_to seen_question_path(question), method: :patch do %>
          <li class="list-group-item d-flex justify-content-between align-items-center text-decoration-none">
            <div class="text-truncate col-9 px-1" > <%=  question.title  %> </div>
            <span class="badge badge-warning badge-pill col-3"><%=  question.updated_at.strftime("%d/%m/%y")  %></span>
          </li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %>
<!-- My campaigns -->
<% if !current_user.organisations.empty? %>
  <div class='d-flex align-items-center justify-content-between mb-2'>
    <h4 class="mt-3">Mes campagnes</h4>
    <h6 class='mt-3 mr-2'>
      <% if current_user.campaigns.count < 3 %>
        <%= link_to new_campaign_path(id: current_user.organisations.all[0].id), class: 'mt-3 mb-1 mr-1' do %>
          <i class="fas fa-plus"></i>
        <% end %>
      <% else %>
        <%= link_to my_campaigns_campaigns_path, class: 'mt-3 mb-1 mr-1' do %>
          <i class="fas fa-arrow-right"></i>
        <% end %>
      <% end %>
    </h6>
  </div>
  <hr class="mb-3">
  <% if !current_user.campaigns.empty? %>
    <% @campaigns.each do |campaign| %>
      <%= link_to dashboard_campaign_path(campaign), class: 'text-decoration-none' do %>
        <div class="d-flex flex-row card card-s">
            <div style="position: absolute" class="d-flex flex-column mt-1 ml-2">
            <% if campaign.questions.where(answer: nil).count > 0 %>
              <span class="text-light mb-0 mt-1 text-decoration-none badge badge-danger badge-pill"><%= "#{campaign.questions.where(answer: nil).count}" %> <i class="fas fa-envelope"></i></span>
            <% end %>
            <% if campaign.end_date <= Date.today %>
              <span class="text-light mb-0 mt-1 text-decoration-none badge badge-info badge-pill">Date <i class="fas fa-exclamation-circle"></i></span>
            <% end %>
            </div>
          <% if campaign.photo.attached? %>
            <%= cl_image_tag campaign.photo.key, crop: :fill %>
          <% else %>
            <img src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
          <% end %>
            <div class="card-body">
              <div class="d-flex justify-content-between align-items-start">
                <div>
                  <h6 style='color: grey' class="mb-0"><%= campaign.name %></h6>
                  <small class='text-truncate' style='max-width: 215px'><%= campaign.organisation.name %></small>
                </div>
                <% if campaign.status == "ongoing" %>
                  <span class="text-decoration-none badge badge-primary badge-pill mb-2"><%= "#{campaign.status}" %></span>
                <% else %>
                  <span class="text-decoration-none badge badge-dark badge-pill mb-2"><%= "#{campaign.status}" %></span>
                <% end %>
              </div>
            </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
  <p class='text-center'>🤨 Pas de campagne en cours...</p>
  <% if current_user.organisations.count == 1 %>
    <%= link_to 'Créer une nouvelle campagne', new_campaign_path(id: current_user.organisations.all[0].id), class: 'btn btn-outline-primary rounded-pill d-block mt-3 plastroc-outline-button w-100' %>
  <% else %>
    <%= link_to 'Créer une nouvelle campagne', new_campaign_path, class: 'btn btn-outline-primary rounded-pill d-block mt-3 plastroc-outline-button w-100' %>
  <% end %>
  <% end %>
<% end %>
  <!-- Classement -->
  <div class='d-flex align-items-center justify-content-between mb-2'>
    <h4 class="mt-3">Classement</h4>
    <h6 class='mt-3 mr-2'>
      <%= link_to users_path, class: 'mt-3 mb-1 mr-1' do %>
        <i class="fas fa-arrow-right"></i>
      <% end %>
    </h6>
  </div>
  <hr class="mb-3">
  <!-- Podium -->
  <div class="container text-center p-2">
    <!-- Top 1 -->
    <div class="d-flex justify-content-between">
      <!-- Top 2 -->
      <div class="justify-content-center p-2">
        <div class="col-4 d-flex p-1">
          <%= image_tag "picto-laurel-gold.png", class: "m-2", style: "object-fit:cover; height: 30px"%>
          <%= cl_image_tag @top_3.first.photo.key, height: 40, width: 40, crop: :fill, class: 'avatar' %>
        </div>
        <p class="mb-0 podium" style=" font-size: 12px; font-weight: 400;"><%= @top_3.first.first_name.first %>. <%= @top_3.first.last_name %></p>
        <p class="mb-0 podium" style=" font-size: 12px; font-weight: 400;"><%= @top_3.first.xp %>xp</p>
      </div>
      <!-- Top 2 -->
      <div class="justify-content-center p-2">
        <div class="col-4 d-flex p-1">
          <%= image_tag "picto-laurel-silver.png", class: "m-2", style: "object-fit:cover; height: 30px"%>
          <%= cl_image_tag @top_3.second.photo.key, height: 40, width: 40, crop: :fill, class: 'avatar' %>
        </div>
        <p class="mb-0 podium" style=" font-size: 12px; font-weight: 400;"><%= @top_3.second.first_name.first %>. <%= @top_3.second.last_name %></p>
        <p class="mb-0 podium" style=" font-size: 12px; font-weight: 400;"><%= @top_3.second.xp %>xp</p>
      </div>
      <!-- Top 3 -->
      <div class="justify-content-center p-2">
        <div class="col-4 d-flex p-1">
          <%= image_tag "picto-laurel-bronze.png", class: "m-2", style: "object-fit:cover; height: 30px"%>
          <%= cl_image_tag @top_3.third.photo.key, height: 40, width: 40, crop: :fill, class: 'avatar' %>
        </div>
        <p class="mb-0 podium" style=" font-size: 12px; font-weight: 400;"><%= @top_3.third.first_name.first %>. <%= @top_3.third.last_name %></p>
        <p class="mb-0 podium" style=" font-size: 12px; font-weight: 400;"><%= @top_3.third.xp %>xp</p>
      </div>
    </div>
  </div>
<!-- Ongoing missions -->
  <div class='d-flex align-items-center justify-content-between mb-2'>
    <h4 class="mt-3">Mes missions</h4>
    <h6 class='mt-3 mr-2'>
      <%= link_to my_missions_missions_path, class: 'mt-3 mb-1 mr-1' do %>
        <i class="fas fa-arrow-right"></i>
      <% end %>
    </h6>
  </div>
  <hr class="mb-3">
  <% if current_user.missions.empty? %>
    <p class='text-center'>🧐 Pas encore de mission en cours...</p>
  <% else %>
    <% @missions.each do |mission| %>
      <%= link_to mission_path(mission), class: 'text-decoration-none' do %>
        <div class="card campaign-card">
          <div class="card-horizontal">
            <div class="img-square-wrapper campaign-card-img">
              <% if mission.package.campaign.photo.attached? %>
                <%= cl_image_tag mission.package.campaign.photo.key, height: 100, width: 100, crop: :fill %>
              <% else %>
                <img style='crop: "fill"; height: 100px; width: 100px;' src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
              <% end %>
            </div>
            <div class="card-content-m p-3 d-flex flex-column justify-content-between align-items-start">
              <div class="m-0 d-flex w-100">
                <span class="mr-1 max-w-100 badge badge-primary rounded-pill mb-1 d-inline-block text-truncate <%= mission.package.name.downcase %>"><%= mission.package.name %>: <%= mission.package.quantity %><%= mission.package.campaign.unit %></span>
                <span class="mr-1 badge badge-info rounded-pill mb-1 d-inline-block text-white"><i class="fas fa-angle-double-up text-white mb-0"></i> <%= mission.package.xp_reward %></span>
                <span class="max-w-100 badge badge-primary rounded-pill mb-1 d-inline-block text-truncate"><%= mission.package.campaign.material.name %></span>
              </div>
              <h6 class="mb-0 max-w-220 text-truncate"><%= mission.package.campaign.organisation.name %></h6>
              <small class='mt-1 max-w-220 p-0 text-truncate'><%= mission.package.campaign.name %></small>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <!-- Si pas d'organisation, possibilité d'en créer une première pour pouvoir créer des campagnes -->
  <% if current_user.organisations.empty? %>
  <hr class="mb-3">
  <p class='text-center'>♻️ Vous êtes recycleur?</p>
    <%= link_to 'Créer une première campagne de recyclage', new_organisation_path, class: 'btn btn-outline-primary rounded-pill d-block mt-3 plastroc-outline-button w-100' %>
  <% end %>
</div>
<!-- nav bar -->
<div class="bottom-nav">
  <div class="d-flex justify-content-between">
    <%= link_to missions_path, class: 'text-decoration-none flex-fill' do %>
      <p class="active-tab"><i class="fas fa-home"></i></p>
    <% end %>
    <%= link_to campaigns_path, class: 'text-decoration-none flex-fill' do %>
      <p class=""><i class="fas fa-search"></i></p>
    <% end %>
    <%= link_to user_path(current_user), class: 'text-decoration-none flex-fill' do %>
      <p class=""><i class=" fas fa-user"></i></p>
    <% end %>
  </div>
</div>
<% if @first_mission_done %>
  <!-- Achivement modal -->
  <div class="achivement-modal d-flex align-items-center">
    <div class="container" id="modal-container">
      <div class="modal-content">
        <div class="modal-body text-center">
        <h4>Félicitations !</h4>
        <% if current_user.missions != [] %>
          <h5><i class="fas fa-plus"></i> <%= current_user.missions.first.package.xp_reward %> xp</h5>
        <% end %>
        <%= image_tag("trophy.png", width: 100, height: 100, class: 'mb-3') %>
        <h6>1ère mission terminée.</h6>
        <p>Aidez nous nous à recruter plus de trieurs en partageant l'application.</p>
       <%= render '/shared/pop_party' %>
        </div>
        <div class="d-flex justify-content-center mb-2">
          <button type="button" id="share-achivement" class="btn btn-primary rounded-pill d-block mt-2 plastroc-button plastroc-light-shadow mr-3">
            <i class="fas fa-share-alt mr-2"></i>Partager
          </button>
          <button type="button" id="share-achivement" class="btn btn-outline-primary rounded-pill d-block mt-2 plastroc-outline-button close-modal">
            </i>Plus tard
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/missions/my_missions.html.erb
<div class="home-banner" style="background-image: url(<%= image_path('leaf-illus.png') %>);">
   <div class="container">
    <div class="d-flex align-items-center justify-content-between">
      <div class="circle d-flex justify-content-center align-items-center plastroc-text-shadow">
        <%= link_to missions_path, class: 'mt-1' do %>
          <i class="fas fa-arrow-left"></i>
        <% end %>
      </div>
      <h3 class="text-left py-4">Missions</h3>
      <div class="circle d-flex justify-content-center align-items-center plastroc-text-shadow">
        <%= link_to campaigns_path, class: 'mt-1' do %>
          <h6 class="m-0"><i class="fas fa-map-marker-alt"></i></h6>
        <% end %>
      </div>
    </div>
   </div>
</div>
<div style="margin-bottom: 72px" class='container'>

<!-- My question's answers if any -->
<% if @questions.count > 0 %>
<p>
  <button class="card d-block mt-2 w-100 border border-primary" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    <div class="d-flex align-items-center justify-content-center">
      <h4 class="m-0 pr-3">📣</h4>
      <p class="mt-3"><strong><%= @questions.count %> réponse(s) à vos questions</strong></p>
    </div>
  </button>
</p>
<div class="collapse" id="collapseExample">
  <div class="card card-body">
    <ul class="list-group">
      <% @questions.each do |question| %>
        <%= link_to seen_question_path(question), method: :patch do %>
        <li class="list-group-item d-flex justify-content-between align-items-center text-decoration-none">
          <div class="text-truncate col-9 px-1" > <%=  question.title  %> </div>
          <span class="badge badge-warning badge-pill col-3"><%=  question.updated_at.strftime("%d/%m/%y")  %></span>
        </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

<!-- Ongoing missions -->

<!-- Tabs -->
<nav class="nav plastroc-tabs d-flex justify-content-around flex-nowrap py-3">
  <a class="active" href="#tab-ongoing" data-toggle="tab">En cours</a>
  <a class="" href="#tab-done" data-toggle="tab">Terminées</a>
</nav>
<hr class="mb-3">

<div class="tab-content" style="margin-bottom: 75px;">

  <!-- Tab Ongoing -->
  <div class="tab-pane active" id="tab-ongoing">
    <% if current_user.missions.empty? %>
      <p class='text-center'>🧐 Pas encore de mission en cours...</p>
    <% else %>
      <% @ongoing_missions.each do |mission| %>
        <%= link_to mission_path(mission), class: 'text-decoration-none' do %>
          <div class="card campaign-card">
            <div class="card-horizontal">
              <div class="img-square-wrapper campaign-card-img">
                <% if mission.package.campaign.photo.attached? %>
                  <%= cl_image_tag mission.package.campaign.photo.key, height: 100, width: 100, crop: :fill %>
                <% else %>
                  <img src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
                <% end %>
              </div>
              <div class="card-content-m p-3 d-flex flex-column justify-content-between align-items-start">
                <div class="m-0 d-flex w-100">
                  <span class="mr-1 max-w-100 badge badge-primary rounded-pill mb-1 d-inline-block text-truncate <%= mission.package.name.downcase %>"><%= mission.package.name %>: <%= mission.package.quantity %><%= mission.package.campaign.unit %></span>
                  <span class="mr-1 badge badge-info rounded-pill mb-1 d-inline-block text-white"><i class="fas fa-angle-double-up text-white mb-0"></i> <%= mission.package.xp_reward %></span>
                  <span class="max-w-100 badge badge-primary rounded-pill mb-1 d-inline-block text-truncate"><%= mission.package.campaign.material.name %></span>
                </div>
                <h6 class="mb-0 max-w-220 text-truncate"><%= mission.package.campaign.organisation.name %></h6>
                <small class='mt-1 max-w-220 p-0 text-truncate'><%= mission.package.campaign.name %></small>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>


    <!-- Tab Done -->
  <div class="tab-pane" id="tab-done">
    <% if current_user.missions.done.empty? %>
      <p class='text-center'>🧐 Pas encore de mission terminée...</p>
    <% else %>
      <% @done_missions.each do |mission| %>
        <%= link_to mission_path(mission), class: 'text-decoration-none' do %>
          <div class="card campaign-card">
            <div class="card-horizontal">
              <div class="img-square-wrapper campaign-card-img">
                <% if mission.package.campaign.photo.attached? %>
                  <%= cl_image_tag mission.package.campaign.photo.key, height: 100, width: 100, crop: :fill %>
                <% else %>
                  <img src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
                <% end %>
              </div>
              <div class="card-content-m p-3 d-flex flex-column justify-content-between align-items-start">
                <div class="m-0 d-flex w-100">
                  <span class="mr-1 max-w-100 badge badge-primary rounded-pill mb-1 d-inline-block text-truncate <%= mission.package.name.downcase %>"><%= mission.package.name %>: <%= mission.package.quantity %><%= mission.package.campaign.unit %></span>
                  <span class="mr-1 badge badge-info rounded-pill mb-1 d-inline-block text-white"><i class="fas fa-angle-double-up text-white mb-0"></i> <%= mission.package.xp_reward %></span>
                  <span class="max-w-100 badge badge-primary rounded-pill mb-1 d-inline-block text-truncate"><%= mission.package.campaign.material.name %></span>
                </div>
                <h6 class="mb-0 max-w-220 text-truncate"><%= mission.package.campaign.organisation.name %></h6>
                <small class='mt-1 max-w-220 p-0 text-truncate'><%= mission.package.campaign.name %></small>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/missions/new.html.erb
<div class=" d-flex flex-column justify-content-between my-4" style="margin-bottom: 75px;">

  <div class="container">
    <div class="d-flex flex-column align-items-center mission-confirmation">
      <% if @campaign.organisation.photo.attached? %>
        <%= cl_image_tag @campaign.organisation.photo.key, height: 56, width: 56, crop: :fill, class: "avatar-large mb-2"%>
      <% else %>
        <img src="https://images.unsplash.com/photo-1536939459926-301728717817?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="">
      <% end %>
      <h5 class="mb-0"><%= @campaign.name %></h5>
      <h6>by <%= @campaign.organisation.name %></h6>
    </div>
  </div>
  <span class="green-separator"></span>
  <div class="d-flex flex-column align-items-center mb-2">
      <h5>Confirmez</h5>
      <h5>votre participation</h5>
  </div>
  <%= link_to 'annuler', campaign_path(@campaign), class: 'm-auto btn btn-outline-primary rounded-pill plastroc-outline-button'%>
  <div class="container mb-4">
      <div class="package-badge package-badge-fluid mt-3 d-flex align-items-center">
          <div class="container p-3">
              <div class="d-flex justify-content-between align-items-center text-left">
                  <div>
                      <p class="mb-1">Votre mission</p>
                      <h6 class="mb-0 badge-pill <%= @package.name.downcase %>"><%= @package.name %></h6>
                  </div>
                  <p class="mb-0"><i class="fas fa-weight-hanging text-primary"></i> <%= @package.quantity %><%= @campaign.unit %></p>
                  <p class="mb-0"><i class="fas fa-angle-double-up text-primary"></i> <%= @package.xp_reward %>xp</p>
              </div>
          </div>
      </div>
  </div>
  <div class="container mb-4">
    <div class="package-badge">
      <div class="p-3" id="confirmation">
        <p class="mb-3">Vous vous engagez à :</p>
        <ul id="engagements">
          <li class=""><span class="ml-2">respecter les quantités</span></li>
          <li class=""><span class="ml-2">respecter le type de matériaux</span></li>
          <li class=""><span class="ml-2">respecter les délais</span></li>
          <li class=""><span class="ml-2">mettre à jour le status de votre mission en cas d'abandon</span></li>
        </ul>

        <label class="checkbox">Je m'engage
            <input type="checkbox" id="confirm">
            <span class="checkmark"></span>
        </label>
    </div>
    </div>
  </div>
</div>

<%= simple_form_for [@campaign, @package, @mission] do |f| %>
  <%= f.submit "Let's go", id: "btn-confirm", class: 'plastroc-button-sticky-bottom btn btn-primary d-block mt-3 plastroc-button plastroc-light-shadow w-100 py-3 disabled'%>
<% end %>